jGnash will now restart automatically for Linux and OSX users after downloading the JavaFX dependencies.

diff --git a/jGnash b/jGnash
--- a/jGnash
+++ b/jGnash
@@ -2,3 +2,9 @@
 
 cwd=$(dirname "$0")
 "$cwd"/bin/bootloader "$@"
+
+if [ $? -eq 100 ]; then #relaunch automatically if return value is 100
+  "$cwd"/bin/bootloader "$@"
+fi
+
+exit 0
